apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  labels:
    name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        args:
        - netexec
        - --http-port=8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: hello-world