apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "${INTERNAL_IP}"
# port: 20250
# serializeImagePulls: false
# evictionHard:
#     memory.available:  "100Mi"
#     nodefs.available:  "10%"
#     nodefs.inodesFree: "5%"
#     imagefs.available: "15%"

# lets look at the join command

#--patches string                                Path to a directory that contains files named "target[suffix][+patchtype].extension". For example, "kube-apiserver0+merge.yaml" or just "etcd.json". "target" can be one of "kube-apiserver", "kube-controller-manager", "kube-scheduler", "etcd", "kubeletconfiguration". "patchtype" can be one of "strategic", "merge" or "json" and they match the patch formats supported by kubectl. The default "patchtype" is "strategic". "extension" must be either "json" or "yaml". "suffix" is an optional string that can be used to determine which patches are applied first alpha-numerically.