- name: Install python
  hosts: all
  become: yes
  tasks:
  - name: Install python3.11
    apt:
      name: python3.11
      state: present

  - name: Install python3.11-dev
    apt:
      name: python3.11-dev
      state: present

  - name: Install python3.11-venv
    apt:
      name: python3.11-dev
      state: present
