- name: Install consul
  hosts: consul*
  become: yes
  tasks:
  - name: Add hashicorp asc key
    ansible.builtin.get_url:
      url: https://apt.releases.hashicorp.com/gpg
      dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
      mode: '0644'
      force: true
  - name: Add hashicorp repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com jammy main"
      state: present
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install consul
    apt:
      name: consul
      state: present
